# Generated by Django 4.0 on 2021-12-15 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='000-0000', max_length=200)),
                ('name', models.CharField(default='Unnamed', max_length=200)),
                ('description', models.CharField(default='N/A', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('date_entry', models.DateTimeField(default=datetime.datetime(2021, 12, 15, 16, 28, 52, 850926, tzinfo=utc))),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
